package io.github.grantchan.sshengine.common.transport.kex;

import io.github.grantchan.sshengine.common.NamedObject;
import io.github.grantchan.sshengine.common.SshException;
import io.github.grantchan.sshengine.util.buffer.Bytes;

import javax.crypto.KeyAgreement;
import java.math.BigInteger;
import java.security.InvalidKeyException;
import java.security.KeyFactory;
import java.security.NoSuchAlgorithmException;
import java.security.spec.InvalidKeySpecException;
import java.security.spec.KeySpec;
import java.util.Objects;

public abstract class Kex implements NamedObject {

  BigInteger pubKey;         // public key generated by this machine
  BigInteger receivedPubKey; // public key generated by peer machine, sent by peer

  KeyAgreement ka;
  private BigInteger sharedKey; // secret key shared by both sides

  abstract KeySpec getKeySpec();

  public BigInteger getPubKey() {
    return this.pubKey;
  }

  public BigInteger getReceivedPubKey() {
    return this.receivedPubKey;
  }

  public void receivedPubKey(BigInteger key) {
    this.receivedPubKey = key;
  }

  public BigInteger getSecretKey() throws SshException {
    if (sharedKey != null) {
      return sharedKey;
    }

    try {
      KeyFactory kf = KeyFactory.getInstance(getName());

      KeySpec ks = Objects.requireNonNull(getKeySpec());

      ka.doPhase(kf.generatePublic(ks), true);
    } catch (NoSuchAlgorithmException e) {
      throw new SshException("Failed to create the key factory instance - name:" + getName(), e);
    } catch (InvalidKeySpecException e) {
      throw new SshException("Failed to generate public key via the give specification", e);
    } catch (InvalidKeyException e) {
      throw new SshException("Failed to get to the next phase during the key agreement process", e);
    }

    byte[] k = Objects.requireNonNull(ka.generateSecret());

    int i = 0;
    while (k[i] == 0) {
      i++;
    }

    sharedKey = new BigInteger(Objects.requireNonNull(Bytes.last(k, k.length - i),
        "Failed to negotiate a share secret key."));

    return sharedKey;
  }
}
