package io.github.grantchan.ssh.trans.kex;

import javax.crypto.KeyAgreement;

public abstract class KeyExchange {

  byte[] pubKey;         // public key generated by this machine
  byte[] receivedPubKey; // public key generated by peer machine, sent by peer

  KeyAgreement ka;

  byte[] getPubKey() {
    return this.pubKey;
  }

  byte[] getReceivedPubKey() {
    return this.receivedPubKey;
  }

  void receivedPubKey(final byte[] key) {
    this.receivedPubKey = key;
  }

  abstract byte[] getSecretKey();
}
